robot_name:
  spot
control_mode:
  torque
active_joints:
  - front left shoulder rotation motor
  - front left elbow motor
  - front right shoulder rotation motor
  - front right elbow motor
  - rear left shoulder rotation motor
  - rear left elbow motor
  - rear right shoulder rotation motor
  - rear right elbow motor

max_step_one_episode:
  50
sim_time_step:
  32
